//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultaPagoIVR.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PagoIVR_Model_Entities : DbContext
    {
        public PagoIVR_Model_Entities()
            : base("name=PagoIVR_Model_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<sp_get_cta_UltimaTransaccionPagoOnline_Result> sp_get_cta_UltimaTransaccionPagoOnline()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_cta_UltimaTransaccionPagoOnline_Result>("sp_get_cta_UltimaTransaccionPagoOnline");
        }
    }
}
